# Generated by Django 5.1.1 on 2024-09-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/'),
        ),
    ]
