# Generated by Django 5.1.1 on 2024-09-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_categoria_icon_alter_producto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icon_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
