# Generated by Django 5.1.1 on 2024-09-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_categoria_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
